exp_name: example_playground
batch_size: 1
num_steps: 50
start_step: 0
out_path: out/
seed: 10
share_attn_layers: [0, 1, 2, 3, 4, 5]
share_resnet_layers: [0,1,2,3]
model: playground

share_attn: true
share_cross_attn: true
share_query: true
share_key: true
share_value: false
use_adain: true
use_content_anchor: true
disentangle: true
resnet_mode: hidden

annotation: /data/example/annotation.json
style_cfg_scale: 7.5
tau_attn: 1
tau_feat: 1
